name: ecomerce_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  cupertino_icons: ^1.0.6
  flutter_custom_clippers: ^2.1.0
  get_storage: ^2.0.3
  image_picker: ^1.0.4
  http: ^1.1.0
  sn_progress_dialog: ^1.1.3
  flutter_carousel_widget: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/img/
  uses-material-design: true
